[build]
  base = "frontend/citizen/citizen-app"
  publish = "build"
  command = "npm run build"

  # Skip builds when only backend or other frontends change
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- backend frontend/issuer frontend/verifier"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  
[build.environment]
  NODE_VERSION = "18"