[build]
  base = "frontend/citizen/citizen-app"
  publish = "build"
  command = "npm run build"

[build.ignore]
  paths = ["backend/**", "frontend/issuer/**", "frontend/verifier/**"]


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  
[build.environment]
  NODE_VERSION = "18"