[build]
  base = "frontend/citizen/citizen-app"
  publish = "build"
  command = "npm run build"

  ignore = "ignore"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  
[build.environment]
  NODE_VERSION = "18"