[build]
  base = "frontend/citizen/citizen-app"
  publish = "frontend/citizen/citizen-app/build"
  command = "cd frontend/citizen/citizen-app && npm run build"

[[build.ignore]]
  paths = [
    "src/**",
    "frontend/issuer/**",
    "frontend/verifier/**",
    "README.md",
    "*.json"
  ]


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  
[build.environment]
  NODE_VERSION = "18"